
services:
  vapeshop_app:
    build:
      args:
        user: developer
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: vapeshop_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./public:/var/www/public  # React build will be here
    #   - storage-data:/var/www/storage
    #   - cache-data:/var/www/bootstrap/cache
    networks:
      - vapeshop_network
    depends_on:
      vapeshop_db:
        condition: service_healthy
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: vapeshop_db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    command: php-fpm

  vapeshop_db:
    image: mysql:8.0
    container_name: vapeshop_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - vapeshop_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:latest
    container_name: vapeshop_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    #   - "443:443"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #   - ./docker-compose/nginx/ssl:/etc/nginx/conf.d/ssl
    #   - ./docker-compose/nginx/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf

    depends_on:
      - vapeshop_app
    networks:
      - vapeshop_network

#   node:
#     image: node:22
#     container_name: vapeshop_node
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#     networks:
#       - vapeshop_network
#     command: ["tail", "-f", "/dev/null"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: vapeshop_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: vapeshop_db
      PMA_PORT: 3306
    #   PMA_USER: mytsv_root
    #   PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 0
    networks:
      - vapeshop_network


  redis:
    image: redis/redis-stack:latest
    container_name: vapeshop_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - vapeshop_network
    volumes:
      - redis_data:/data
    # command: redis-server --appendonly yes
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}


networks:
  vapeshop_network:
    driver: bridge

volumes:
  db_data:
  redis_data:
#   storage-data:
#   cache-data:


# cd docker-compose/nginx/ssl/
# openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout self-signed.key -out self-signed.crt
