name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            git config --global --add safe.directory ${{ secrets.EC2_APP_DIR }}
            cd ${{ secrets.APP_DIRECTORY }}
            git pull origin main &&
            sudo docker compose down &&
            sudo docker compose up -d --build &&
            sudo docker compose exec -T -u root peach_app composer install --no-interaction --prefer-dist --optimize-autoloader &&
            sudo docker exec -T -u root vapeshop_app php artisan migrate --force &&
            sudo docker exec -T -u root vapeshop_app php artisan config:cache &&
            sudo docker exec -T -u root vapeshop_app php artisan route:cache &&
            sudo docker exec -T -u root vapeshop_app php artisan optimize:clear &&
            sudo docker exec -T -u root vapeshop_app php artisan queue:restart &&
            sudo chown -R www-data:www-data storage bootstrap/cache &&
            sudo chmod -R 775 storage bootstrap/cache


      # - name: Set up SSH
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
      #     chmod 600 ~/.ssh/id_ed25519
      #     ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # - name: Deploy on EC2
      #   run: |
      #     ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
      #       cd ${{ secrets.APP_DIRECTORY }} &&
      #       git pull origin main &&
      #       sudo docker compose down &&
      #       sudo docker compose up -d --build &&
      #       sudo docker exec vapeshop_app php artisan migrate --force &&
      #       sudo docker exec vapeshop_app php artisan config:cache &&
      #       sudo docker exec vapeshop_app php artisan route:cache &&
      #       sudo docker exec vapeshop_app php artisan optimize:clear &&
      #       sudo docker exec vapeshop_app php artisan queue:restart &&
      #       sudo chown -R www-data:www-data storage bootstrap/cache &&
      #       sudo chmod -R 775 storage bootstrap/cache
      #     "
